version: '3'

services:
  seed:
    image: thummcoin
    container_name: seed
    volumes:
      - .:/go/src/github.com/jeanlucthumm/thummcoin
    command: --seed
    stdin_open: true
    tty: true
  client:
    image: thummcoin
    depends_on:
      - seed
    volumes:
      - .:/go/src/github.com/jeanlucthumm/thummcoin
    stdin_open: true
    tty: true
