// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package prot is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Ping
	PeerList
*/
package prot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ping struct {
	From string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ping) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Ping) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type PeerList struct {
	Peers []*PeerList_Peer `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
}

func (m *PeerList) Reset()                    { *m = PeerList{} }
func (m *PeerList) String() string            { return proto.CompactTextString(m) }
func (*PeerList) ProtoMessage()               {}
func (*PeerList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PeerList) GetPeers() []*PeerList_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type PeerList_Peer struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *PeerList_Peer) Reset()                    { *m = PeerList_Peer{} }
func (m *PeerList_Peer) String() string            { return proto.CompactTextString(m) }
func (*PeerList_Peer) ProtoMessage()               {}
func (*PeerList_Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *PeerList_Peer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Ping)(nil), "prot.Ping")
	proto.RegisterType((*PeerList)(nil), "prot.PeerList")
	proto.RegisterType((*PeerList_Peer)(nil), "prot.PeerList.Peer")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0x58, 0x40, 0x94, 0x92, 0x16, 0x17, 0x4b, 0x40,
	0x66, 0x5e, 0xba, 0x90, 0x10, 0x17, 0x4b, 0x5a, 0x51, 0x7e, 0xae, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x98, 0x2d, 0xc4, 0xc7, 0xc5, 0x54, 0x92, 0x2f, 0xc1, 0x04, 0x16, 0x61, 0x2a, 0xc9,
	0x57, 0x0a, 0xe7, 0xe2, 0x08, 0x48, 0x4d, 0x2d, 0xf2, 0xc9, 0x2c, 0x2e, 0x11, 0xd2, 0xe4, 0x62,
	0x2d, 0x48, 0x4d, 0x2d, 0x2a, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0x06, 0x1b, 0xaa,
	0x07, 0x93, 0x06, 0x33, 0x82, 0x20, 0x2a, 0xa4, 0x14, 0xb8, 0x58, 0x40, 0x5c, 0x21, 0x09, 0x2e,
	0xf6, 0xc4, 0x94, 0x94, 0xa2, 0xd4, 0xe2, 0x62, 0xa8, 0x2d, 0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x45,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xc3, 0x51, 0xd0, 0xa3, 0x00, 0x00, 0x00,
}
