// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package prot is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Message
	Request
	PeerList
*/
package prot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_PING      Type = 0
	Type_REQ       Type = 1
	Type_PEER_LIST Type = 2
)

var Type_name = map[int32]string{
	0: "PING",
	1: "REQ",
	2: "PEER_LIST",
}
var Type_value = map[string]int32{
	"PING":      0,
	"REQ":       1,
	"PEER_LIST": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Request_Type int32

const (
	Request_PEER_LIST Request_Type = 0
)

var Request_Type_name = map[int32]string{
	0: "PEER_LIST",
}
var Request_Type_value = map[string]int32{
	"PEER_LIST": 0,
}

func (x Request_Type) String() string {
	return proto.EnumName(Request_Type_name, int32(x))
}
func (Request_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Message struct {
	Type Type   `protobuf:"varint,1,opt,name=type,enum=prot.Type" json:"type,omitempty"`
	From string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	To   string `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
	// 2 - 10 reserved for inner protocol
	Data []byte `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_PING
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Request struct {
	Type Request_Type `protobuf:"varint,1,opt,name=type,enum=prot.Request_Type" json:"type,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetType() Request_Type {
	if m != nil {
		return m.Type
	}
	return Request_PEER_LIST
}

type PeerList struct {
	Peers []*PeerList_Peer `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
}

func (m *PeerList) Reset()                    { *m = PeerList{} }
func (m *PeerList) String() string            { return proto.CompactTextString(m) }
func (*PeerList) ProtoMessage()               {}
func (*PeerList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PeerList) GetPeers() []*PeerList_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type PeerList_Peer struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *PeerList_Peer) Reset()                    { *m = PeerList_Peer{} }
func (m *PeerList_Peer) String() string            { return proto.CompactTextString(m) }
func (*PeerList_Peer) ProtoMessage()               {}
func (*PeerList_Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *PeerList_Peer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "prot.Message")
	proto.RegisterType((*Request)(nil), "prot.Request")
	proto.RegisterType((*PeerList)(nil), "prot.PeerList")
	proto.RegisterType((*PeerList_Peer)(nil), "prot.PeerList.Peer")
	proto.RegisterEnum("prot.Type", Type_name, Type_value)
	proto.RegisterEnum("prot.Request_Type", Request_Type_name, Request_Type_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xbb, 0xc9, 0x6a, 0x9a, 0xa9, 0x86, 0x30, 0x22, 0x2c, 0x1e, 0x24, 0xe4, 0x20, 0xab,
	0x87, 0x1e, 0xea, 0x6f, 0x08, 0x5a, 0xa8, 0x12, 0xd7, 0x82, 0x47, 0x59, 0xcd, 0x28, 0x82, 0xb2,
	0x71, 0x77, 0x3d, 0xf4, 0xdf, 0x4b, 0x26, 0x2d, 0xb4, 0xa7, 0x7d, 0x6f, 0xe6, 0xb1, 0xdf, 0x63,
	0xa0, 0xe8, 0xbd, 0x8b, 0xee, 0xdd, 0x7d, 0xcf, 0x59, 0xa0, 0x1c, 0x9e, 0xda, 0x42, 0xf6, 0x40,
	0x21, 0xd8, 0x4f, 0xc2, 0x4b, 0x90, 0x71, 0xd3, 0x93, 0x12, 0x95, 0xd0, 0xc5, 0x02, 0x38, 0x36,
	0x5f, 0x6f, 0x7a, 0x32, 0x3c, 0x47, 0x04, 0xf9, 0xe1, 0xdd, 0x8f, 0x4a, 0x2a, 0xa1, 0x73, 0xc3,
	0x1a, 0x0b, 0x48, 0xa2, 0x53, 0x29, 0x4f, 0x92, 0xe8, 0x86, 0x4c, 0x67, 0xa3, 0x55, 0xb3, 0x4a,
	0xe8, 0x13, 0xc3, 0xba, 0xbe, 0x87, 0xcc, 0xd0, 0xef, 0x1f, 0x85, 0x88, 0x57, 0x07, 0x08, 0x1c,
	0x11, 0xdb, 0xe5, 0x1e, 0xaa, 0x3e, 0x07, 0x39, 0x38, 0x3c, 0x85, 0xbc, 0x6d, 0x1a, 0xf3, 0xba,
	0x5a, 0x3e, 0xaf, 0xcb, 0x49, 0xfd, 0x02, 0xd3, 0x96, 0xc8, 0xaf, 0xbe, 0x42, 0xc4, 0x6b, 0x38,
	0xea, 0x89, 0x7c, 0x50, 0xa2, 0x4a, 0xf5, 0x6c, 0x71, 0x36, 0xfe, 0xb5, 0x5b, 0xb3, 0x30, 0x63,
	0xe2, 0xa2, 0x02, 0x39, 0x58, 0x54, 0x90, 0xd9, 0xae, 0xf3, 0x14, 0x02, 0x17, 0xc8, 0xcd, 0xce,
	0xde, 0xe8, 0x2d, 0x6f, 0x0a, 0xb2, 0x5d, 0x3e, 0xde, 0x95, 0x13, 0xcc, 0x20, 0x35, 0xcd, 0x53,
	0x29, 0x0e, 0x2b, 0x24, 0x6f, 0xc7, 0x7c, 0xbc, 0xdb, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d,
	0x71, 0xc9, 0x1e, 0x4e, 0x01, 0x00, 0x00,
}
